# Generated by Django 3.2.6 on 2021-08-09 20:56
from django.db import migrations


def load_initial_data(apps, schema_editor):
    data = [
        {"name": "electricity", "unit": "kwh", "factor": 1.5},
        {"name": "water", "unit": "kg", "factor": 26.93},
        {"name": "heating", "unit": "kwh", "factor": 3.892},
        {"name": "heating", "unit": "l", "factor": 8.57},
        {"name": "heating", "unit": "m3", "factor": 19.456},
    ]
    usage_types = apps.get_model("usage", "UsageTypes")
    for item in data:
        new = usage_types(name=item["name"], unit=item["unit"], factor=item["factor"])
        new.save()


class Migration(migrations.Migration):
    dependencies = [
        ("usage", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_initial_data)]
